latest patch from rycee

diff --git a/net/net-tools/ifup b/net/net-tools/ifup
--- a/net/net-tools/ifup
+++ b/net/net-tools/ifup
@@ -3,16 +3,72 @@
 # $1 - needle
 exists_in_text()
 {
-  [ "$1" == "" ] && return 0
+  [ "$1" = "" ] && return 0
 
   IFS=" 	
 "
 
   for x in $( cat ) ; do
-    [ "$1" == "$x" ] && return 0
+    [ "$1" = "$x" ] && return 0
   done
 
   return 1
+}
+
+_do_device_up()
+{
+  if [ "$MODE" = dynamic ]; then
+    . /etc/sysconfig/dhcpcd
+    ARGS=""
+    [ "$USE_SYSLOG" = "yes" ] && ARGS="-d"
+
+    echo "Starting dhcpcd on $DEV ..."
+    if [ -e $DHCPCD_PATH$DEV.pid ]; then
+      dhcpcPid=`cat $DHCPCD_PATH$DEV.pid`
+      dhcpcd -k $DEV 1>/dev/null 2>&1 &&
+      renice 10 $dhcpcPid 1>/dev/null 2>&1 || rm -f $DHCPCD_PATH$DEV.pid &&
+      sleep 1
+    fi &&
+    dhcpcd -t $TIMEOUT $ARGS $DEV
+  elif [ "$MODE" = static ]; then
+    echo "Setting up static networking on $DEV..."
+    ARGS=""
+    if [ "$POINTOPOINT" != "" ] ; then
+      ARGS="$ARGS pointopoint $POINTOPOINT"
+    fi
+    if [ "$MTU" != "" ] ; then
+      ARGS="$ARGS mtu $MTU"
+    fi
+
+    ifconfig $DEV $IP broadcast $BROADCAST netmask $NETMASK $ARGS
+  else
+    echo "There are errors in $netdevdir/$DEV.dev"
+    exit 1
+  fi
+}
+
+_do_route_up()
+{
+  # check if GATEWAY is set; gateway is set by PPP or other software in some
+  # cases
+  if [ "$GATEWAY" ]; then
+    route add default gateway $GATEWAY dev $DEV
+  fi 
+}
+
+_on_up()
+{
+  true
+}
+
+# Handles function "overloading"
+run_func() {
+  # If for example do_route_up exists then run it, otherwise run _do_route_up
+  if [ "$( type -t $1 )" = function ] ; then
+    $1
+  else
+    _$1
+  fi
 }
 
 netdevdir=/etc/sysconfig/network
@@ -31,12 +87,13 @@ if [ ! -f $netdevdir/$DEV.dev ]; then
   exit 1
 fi
 
-if /sbin/ifconfig $DEV 2>&1 | exists_in_text UP ; then
+if /sbin/ifconfig 2>&1 | exists_in_text $DEV ; then
   echo "$DEV already up"
   exit 0
 fi
 
-unset MODE MODULE IP BROADCAST NETMASK GATEWAY
+unset MODE MODULE IP BROADCAST NETMASK GATEWAY POINTOPOINT MTU UP_ON_BOOT
+unset do_device_up do_route_up on_up
 
 . $netdevdir/$DEV.dev
 
@@ -45,34 +102,15 @@ if [ -z "$MODE" ]; then
   exit 1
 fi
 
+if [ "${_OBEY_UP_ON_BOOT}" = 1 -a "$UP_ON_BOOT" = no ] ; then
+  exit 0
+fi
+
 if [ "$MODULE" ] && ! /sbin/lsmod | exists_in_text "$MODULE" ; then
   echo "Loading module $MODULE for $DEV ..."
   modprobe  $MODULE
-fi
+fi &&
 
-if [ "$MODE" = dynamic ]; then
-  . /etc/sysconfig/dhcpcd
-  ARG=""
-  [ "$USE_SYSLOG" = "yes" ] && ARG="-d"
-
-  echo "Starting dhcpcd on $DEV ..."
-  if [ -e $DHCPCD_PATH$DEV.pid ]; then
-    dhcpcPid=`cat $DHCPCD_PATH$DEV.pid`
-    dhcpcd -k $DEV 1>/dev/null 2>&1 &&
-    renice 10 $dhcpcPid 1>/dev/null 2>&1 || rm -f $DHCPCD_PATH$DEV.pid &&
-    sleep 1
-  fi &&
-  dhcpcd -t $TIMEOUT $ARG $DEV
-elif [ "$MODE" = static ]; then
-  echo "Setting up static networking on $DEV..."
-  ifconfig  $DEV $IP broadcast $BROADCAST netmask $NETMASK &&
-
-  # check if GATEWAY is set; gateway is set by PPP or other software in some
-  # cases
-  if [ "$GATEWAY" ]; then
-    route add default gateway $GATEWAY dev $DEV
-  fi
-else
-  echo "There are errors in $netdevdir/$DEV.dev"
-  exit 1
-fi
+run_func do_device_up &&
+run_func do_route_up &&
+run_func on_up
