init.d feature bloat

diff --git a/smgl/init.d/files/rc b/smgl/init.d/files/rc
--- a/smgl/init.d/files/rc
+++ b/smgl/init.d/files/rc
@@ -21,6 +21,7 @@ RUNLEVELS_DIR="/etc/init.d/runlevels"
 
 # Get some configurations that alter the behavior of this script
 . /etc/sysconfig/init
+. /etc/init.d/smgl_functions
 
 
 essential_script_failure()
@@ -71,6 +72,8 @@ start()
 # $1 - requested runlevel
 run_runlevel()
 {
+  [ $# -eq 0 ] && echo "missing runlevel argument" > /dev/stderr && exit 1
+  local OK_ERR=
   (
     lvl=$1
     lvl_file="$RUNLEVELS_DIR/%$1"
@@ -85,10 +88,11 @@ run_runlevel()
     elif [ -f "$lvl_file" -a -x "$lvl_file" ] ; then
       . $lvl_file
     else
-      echo "not a runlevel: $lvl"
-      exit 0
+      echo "not a runlevel: $lvl" > /dev/stderr
+      OK_ERR=1
     fi
   ) || essential_script_failure
+  [ -n "$OK_ERR" ] && exit 1
 }
 
 # $1 - requested script
@@ -97,18 +101,223 @@ run_script()
 {
   local script=$1
   shift 2
-  $RUNLEVELS_DIR/*/$script "$@"
+  if [ $# -gt 0 ] ; then
+    $RUNLEVELS_DIR/*/$script "$@"
+  else
+    echo "missing script argument" > /dev/stderr && exit 1
+  fi
 }
 
-# $1 - target runlevel
-# alternatively
-# $1 - script to run
-# $@ - script argument
+run_enable()
+{
+  local i
+  for i in $*; do
+    local FILE="$(ls $RUNLEVELS_DIR/*/"$i")"
+    if [ ! -x "$FILE" ]; then
+      chmod ug+x "$FILE" && echo "Service $i successfully enabled." && run_script "$i" "$i" start ||
+      ( echo "an error occurred enabling service $i" > /dev/stderr && exit 1 )
+    else
+      echo "Service $i already enabled." > /dev/stderr
+      INIT_FAIL_LOG=yes
+    fi
+  done
+}
+
+run_disable()
+{
+  local i
+  for i in $*; do
+    local FILE="$(ls $RUNLEVELS_DIR/*/"$i")"
+    local SKIP=
+    if [ -x "$FILE" ]; then
+      . /etc/sorcery/config
+      if grep -Fq 'ESSENTIAL=yes' "$FILE" ; then query "Are you sure you want to disable this ESSENTIAL script?" n || SKIP=yes; fi
+      if [ -z "$SKIP" ] ; then
+        run_script "$i" "$i" stop  && chmod ug-x "$FILE" && echo "Service $i successfully disabled." ||
+          ( echo "an error occurred disabling service $i" > /dev/stderr && exit 1 )
+      else
+        echo "ESSENTIAL service $i skipped."
+      fi
+    else
+      echo "Service $i already disabled." > /dev/stderr
+      INIT_FAIL_LOG=yes
+    fi
+  done
+}
+
+run_delete()
+{
+  local i
+  for i in $*; do
+    local FILE="$(ls $RUNLEVELS_DIR/*/"$i")"
+    local SKIP=
+    if [ ! -x "$FILE" ]; then
+      . /etc/sorcery/config
+      if grep -Fq 'ESSENTIAL=yes' "$FILE" ; then
+        query "Are you sure you want to DELETE this ESSENTIAL script?" n || SKIP=yes
+      else
+        query "Are you sure you want to DELETE this script?" n || SKIP=yes
+      fi
+      if [ -z "$SKIP" ] ; then
+        rm "$FILE" && echo "Service $i successfully deleted." ||
+          ( echo "an error occurred deleting service $i" > /dev/stderr && exit 1 )
+      else
+        echo "Delete of service $i skipped."
+      fi
+    else
+      echo "Service $i is enabled, please disable it first." > /dev/stderr
+      INIT_FAIL_LOG=yes
+    fi
+  done
+}
+
+run_bootenable()
+{
+  local i
+  for i in $*; do
+    local FILE="$(ls $RUNLEVELS_DIR/*/"$i")"
+    if [ ! -x "$FILE" ]; then
+      chmod ug+x "$FILE" && echo "Service $i successfully enabled." ||
+      ( echo "an error occurred enabling service $i" > /dev/stderr && exit 1 )
+    else
+      echo "Service $i already enabled." > /dev/stderr
+      INIT_FAIL_LOG=yes
+    fi
+  done
+}
+
+run_bootdisable()
+{
+  local i
+  for i in $*; do
+    local FILE="$(ls $RUNLEVELS_DIR/*/"$i")"
+    local SKIP=
+    if [ -x "$FILE" ]; then
+      . /etc/sorcery/config
+      if grep -Fq 'ESSENTIAL=yes' "$FILE" ; then query "Are you sure you want to disable this ESSENTIAL script?" n || SKIP=yes; fi
+      if [ -z "$SKIP" ] ; then
+        chmod ug-x "$FILE" && echo "Service $i successfully disabled." ||
+          ( echo "an error occurred disabling service $i" > /dev/stderr && exit 1 )
+      else
+        echo "ESSENTIAL service $i skipped."
+      fi
+    else
+      echo "Service $i already disabled." > /dev/stderr
+      INIT_FAIL_LOG=yes
+    fi
+  done
+}
+
+run_enabled()
+{ 
+  ls -l "$RUNLEVELS_DIR"/*/* | grep -v runlevel.config$ | grep "^...x..x" | sed -e 's!^.*/!!'
+}
+
+run_disabled()
+{ 
+  ls -l "$RUNLEVELS_DIR"/*/* | grep -v runlevel.config$ | grep -v "^...x..x" | sed -e 's!^.*/!!'
+}
+
+run_list()
+{ 
+  echo "RUNLEVEL SCRIPT"
+  ls -l "$RUNLEVELS_DIR"/*/* | grep -v runlevel.config | sed -e 's!^.*/%\(.*\)/!\1        !'
+}
+
+run_move()
+{
+  local FILE="$(ls $RUNLEVELS_DIR/*/"$1" 2> /dev/null)"
+  if [ -f "$FILE" ] ; then
+    if [ -d "$RUNLEVELS_DIR/%$2" ] ; then
+      local OLD_RUNLEVEL="$(echo "$FILE" | sed -e 's!^/.*/%!!' | cut -d'/' -f1)"
+      if [ "$OLD_RUNLEVEL" != "$2" ] ; then
+        mv "$FILE" "$RUNLEVELS_DIR/%$2" &&
+        echo "Script $1 moved from runlevel $OLD_RUNLEVEL to runlevel $2." || exit 1
+      else
+        echo "Script $1 already in runlevel $2." && exit 1
+      fi
+    else
+      echo "runlevel $2 is not a valid runlevel container." > /dev/stderr
+      echo "valid runlevel containers are:" > /dev/stderr
+      ls -ld "$RUNLEVELS_DIR"/* | grep "^d" | sed -e 's!^.*/%!!' > /dev/stderr
+      exit 1
+    fi
+  else
+    echo "script $1 does not exist" > /dev/stderr
+    exit 1
+  fi
+}
+
+run_runlevels()
+{
+  echo "TYPE RUNLEVEL"
+  ls -ld "$RUNLEVELS_DIR"/%* | sed -e 's! -> /.*/%! -> !' -e 's!^\(.\).*/%!\1    !'
+}
+
+run_install()
+{
+  if [ -f "$1" ] ; then
+    if [ -d "$RUNLEVELS_DIR/%$2" ] ; then
+      cp "$1" "$RUNLEVELS_DIR/%$2" &&
+      echo "Script $1 installed to runlevel $2." || exit 1
+    else
+      echo "runlevel $2 is not a valid runlevel container." > /dev/stderr
+      echo "valid runlevel containers are:" > /dev/stderr
+      ls -ld "$RUNLEVELS_DIR"/* | grep -v "^d" | sed -e 's!^.*/%!!' > /dev/stderr
+      exit 1
+    fi
+  else
+    echo "file $1 does not exist" > /dev/stderr
+    exit 1
+  fi
+}
+
 telinit()
 {
-  if    [ $# -eq 1 ] ; then run_runlevel $1
-  elif  [ $# -gt 1 ] ; then run_script $1 "$@"
-  fi
+  local FAIL=no
+  (
+  INIT_FAIL_LOG=
+  case "$1" in
+    run)           shift; run_script       "$1" "$@" ;;
+    switch)        shift; run_runlevel     "$1"      ;;
+    enable)        shift; run_enable       "$@"      ;;
+    disable)       shift; run_disable      "$@"      ;;
+    bootenable)    shift; run_bootenable   "$@"      ;;
+    bootdisable)   shift; run_bootdisable  "$@"      ;;
+    delete)        shift; run_delete       "$@"      ;;
+    enabled)       shift; run_enabled                ;;
+    disabled)      shift; run_disabled               ;;
+    list)          shift; run_list                   ;;
+    runlevels)     shift; run_runlevels              ;;
+    move)          shift; run_move         "$1" "$2" ;;
+    install)       shift; run_install      "$1" "$2" ;;
+    *)             cat > /dev/stderr << EOF
+usage:
+telinit run <script> [<args>]        run init <script> with arguments <args>
+telinit switch <rlvl>                switch to runlevel <rlvl>
+telinit enable [<script> ... ]       enable and start <script> if not enabled
+telinit disable [<script> ... ]      stop and disable <script> if not disabled
+telinit bootenable [<script> ... ]   enable <script> if not enabled
+telinit bootdisable [<script> ... ]  disable <script> if not disabled
+telinit delete [<script> ... ]       delete <script> if disabled
+telinit enabled                      list enabled startup scripts
+telinit disabled                     list disabled startup scripts
+telinit list                         list startup scripts and their runlevels
+telinit runlevels                    list all runlevels
+telinit move <script> <rlvl>         move <script> to runlevel <rlvl>
+telinit install <file> <rlvl>        install <file> into runlevel <rlvl>
+EOF
+    exit 1
+    ;;
+  esac
+  [ "$INIT_FAIL_LOG" == "yes" ]  && exit 1
+  true
+  ) || FAIL=yes
+  case "$1" in
+    run|switch|enabled|disabled|list|runlevels) exit 0 ;;
+  esac
+  [ "$FAIL" == "no" ]  ;  evaluate_retval
+  [ "$FAIL" == "yes" ] && exit 1
 }
 
 
