by rycee - submitting for him

diff --git a/smgl/init.d/files/smgl_init b/smgl/init.d/files/smgl_init
--- a/smgl/init.d/files/smgl_init
+++ b/smgl/init.d/files/smgl_init
@@ -109,9 +109,62 @@ handle_provides()
   fi
 }
 
+# $1 - action to take (abort, ask, ignore)
+_handle_essential_failure()
+{
+  case "$1" in
+    ignore) exit $exit_code
+            ;;
+    abort)  echo "Starting rescue shell, the computer will be rebooted"
+            echo "when logging out..."
+            /sbin/sulogin
+            /sbin/reboot
+            ;;
+    ask)    echo "Which action do you wish to take?"
+            while true ; do
+              read -n 1 -p "[a]bort, [i]gnore: " in
+              echo
+              case "$in" in
+                a)    _handle_essential_failure abort   ;;
+                i)    _handle_essential_failure ignore  ;;
+                *)    continue                          ;;
+              esac
+              break   # Just to be sure we don't get an infinite loop
+            done
+            ;;
+    *)      echo -n "Bad value specified for ESSENTIAL_FAIL_ACTION: "
+            echo $ESSENTIAL_FAIL_ACTION
+            ;;
+  esac
+}
+
+_handle_exit()
+{
+  if [ "$1" = "start" ] ; then
+    if [ $exit_code -eq 0 -a "$PROGRAM" ] ; then
+      ( . /etc/init.d/auto_init ; )
+      exit_code=$?
+    fi
+
+    if [ $exit_code -ne 0 -a "$ESSENTIAL" = "yes" ] ; then
+      . /etc/sysconfig/init
+      echo
+      echo "Essential script failed..."
+      echo
+      _handle_essential_failure "$ESSENTIAL_FAIL_ACTION"
+    fi
+  else
+    if [ $exit_code -eq 0 -a "$PROGRAM" ] ; then
+      . /etc/init.d/auto_init
+    else
+      exit $exit_code
+    fi
+  fi
+}
 
 ##################################
 
+trap 'exit_code=$? _handle_exit "$@"' EXIT
 
 # Do this in a sub-shell to not pollute namespace with content of facilities.
 if [ "$1" = "start" ] ; then
@@ -123,15 +176,6 @@ if [ "$1" = "start" ] ; then
     handle_needs
     handle_provides
   ) || exit $?
-fi
-
-
-#########################
-# Handle PROGRAM variable
-
-# If auto_init is wanted then source it when the parent script exists
-if [  "$PROGRAM"  ] ; then
-  trap 'ret=$? ; [ $ret -eq 0 ] && . /etc/init.d/auto_init || exit $ret' EXIT
 fi
 
 
