added custom kernel

diff --git a/kernels/linux-new/PREPARE b/kernels/linux-new/PREPARE
--- a/kernels/linux-new/PREPARE
+++ b/kernels/linux-new/PREPARE
@@ -401,6 +401,50 @@ options_menu()
 	done
 }
 
+custom_kernel()
+{
+	. $latestdefaults
+	command=$($dialog --inputbox "Which Kernel do you want to build?\nYou can enter any valid version number.\nExamples:\nLATEST_PRE_2_4\nLATEST_ac_patches\n${LATEST_2_6}" 0 0 ${kver})
+	retval=$?
+	echo $command
+	case "$command" in
+		LATEST_2*)
+			kver="$command"
+			;;
+		LATEST*)
+			selected_patches="$command"
+			;;
+		*)
+			release=${command%%-*}
+			prerelease=${release}
+			major=${release%%\.*}
+			major_tail=${command#$major\.}
+			minor=${major_tail%%\.*}
+			tree=$major.$minor
+			tail=${command#$release}
+			selected_patches=""
+			while [[ $tail == -* ]]
+			do
+				patch=${tail##*-}
+				tail=${tail%-$patch}
+				echo $patch
+				if [[ $patch == ac* ]] || [[ $patch == ck* ]]; then
+					selected_patches="patch-${release}-${patch} ${selected_patches}"
+				elif [[ $patch == pre* ]] || [[ $patch == rc* ]]; then
+					release=${tree}.$((${prerelease#${tree}.*}-1))  # Reduce Version number by one
+					selected_patches="patch-${prerelease}-${patch} ${selected_patches}"
+				elif [[ $patch == mm* ]]; then
+					selected_patches="${command} ${selected_patches}"
+				else
+					echo "Failed parsing patches"  &&
+					return  1
+				fi
+				
+			done
+			;;
+	esac
+}
+
 # create a new linux source tree
 # I use awk to parse the latest.defaults file
 # that should be changed but how?
@@ -432,8 +476,7 @@ new_tree_menu()
 					patch_menu $kver
 					;;
 				CUSTOM*)
-					echo "Not Implemented Yet"
-					sleep 5
+					custom_kernel
 					;;
 				*) 
 					break 
