integrated reiser4 from devel and fixed custom kernel selection from devel

diff --git a/kernels/linux/PREPARE b/kernels/linux/PREPARE
--- a/kernels/linux/PREPARE
+++ b/kernels/linux/PREPARE
@@ -133,7 +133,8 @@ main_menu()
 		"Would you like to use a new kernel tree or an existing one?\nThe Current kernel is $kver\nThe current selected patches: ${selected_patches}" 0 0 0 \
 		"newktree" "New Kernel Tree" "I want to use a new kernel tree"  \
 		"oldktree" "Old Kernel Tree" "I want to use an old kernel tree"  \
-		"Options" "Menu" "Kernel Arch, Build Dir, Cleaning" )
+		"expert"   "User Generated Kernel Tree" "I want to use a kernel tree that I made" \
+		"Options"  "Menu" "Kernel Arch, Build Dir, Cleaning" )
 		retval="$?"
 		if [ "$retval" == "0" ]
 		then
@@ -145,6 +146,10 @@ main_menu()
 				"oldktree")
 					mode=$command
 					old_src_menu
+					;;
+				"expert")
+					mode=$command
+					custom_kernel
 					;;
 				"Options")
 					options_menu
@@ -393,45 +398,52 @@ options_menu()
 custom_kernel()
 {
 	. $latestdefaults
-	command=$("${dialog[@]}" --inputbox "Which Kernel do you want to build?\nYou can enter any valid version number.\nExamples:\nLATEST_PRE_2_4\nLATEST_ac_patches\n${LATEST_2_6}" 0 0 ${kver})
+	command=$("${dialog[@]}" --inputbox "Enter the kernel version for the source you want to build?\nExamples:\n2.4.31\n2.6.13.4-selinux1\n${LATEST_2_6}" 0 0 "")
 	retval=$?
 	echo $command
-	case "$command" in
-		LATEST_2*)
-			kver="$command"
-			;;
-		LATEST*)
-			selected_patches="$command"
-			;;
-		*)
-			release=${command%%-*}
-			prerelease=${release}
-			major=${release%%\.*}
-			major_tail=${command#$major\.}
-			minor=${major_tail%%\.*}
-			tree=$major.$minor
-			tail=${command#$release}
-			selected_patches=""
-			while [[ $tail == -* ]]
-			do
-				patch=${tail##*-}
-				tail=${tail%-$patch}
-				echo $patch
-				if [[ $patch == ac* ]] || [[ $patch == ck* ]]; then
-					selected_patches="patch-${release}-${patch} ${selected_patches}"
-				elif [[ $patch == pre* ]] || [[ $patch == rc* ]]; then
-					release=${tree}.$((${prerelease#${tree}.*}-1))  # Reduce Version number by one
-					selected_patches="patch-${prerelease}-${patch} ${selected_patches}"
-				elif [[ $patch == mm* ]]; then
-					selected_patches="${command} ${selected_patches}"
-				else
-					echo "Failed parsing patches"  &&
-					return  1
-				fi
-				
-			done
-			;;
-	esac
+	if [[ "$?" == "0" ]] 
+	then
+		kver=$command
+		old_src_tree="/usr/src/linux-${kver}"
+		selected_patches=""
+		patches=""
+	fi
+#	case "$command" in
+#		LATEST_2*)
+#			kver="$command"
+#			;;
+#		LATEST*)
+#			selected_patches="$command"
+#			;;
+#		*)
+#			release=${command%%-*}
+#			prerelease=${release}
+#			major=${release%%\.*}
+#			major_tail=${command#$major\.}
+#			minor=${major_tail%%\.*}
+#			tree=$major.$minor
+#			tail=${command#$release}
+#			selected_patches=""
+#			while [[ $tail == -* ]]
+#			do
+#				patch=${tail##*-}
+#				tail=${tail%-$patch}
+#				echo $patch
+#				if [[ $patch == ac* ]] || [[ $patch == ck* ]]; then
+#					selected_patches="patch-${release}-${patch} ${selected_patches}"
+#				elif [[ $patch == pre* ]] || [[ $patch == rc* ]]; then
+#					release=${tree}.$((${prerelease#${tree}.*}-1))  # Reduce Version number by one
+#					selected_patches="patch-${prerelease}-${patch} ${selected_patches}"
+#				elif [[ $patch == mm* ]]; then
+#					selected_patches="${command} ${selected_patches}"
+#				else
+#					echo "Failed parsing patches"  &&
+#					return  1
+#				fi
+#				
+#			done
+#			;;
+#	esac
 }
 
 # create a new linux source tree
@@ -447,7 +459,7 @@ new_tree_menu()
 		do
 			menu="${menu}${version} Linux_Kernel Select_one "
 		done
-		menu="CUSTOM Linux_Kernel Enter_your_own_version $( awk -F= '$1 ~ /LATEST_2/ {print $1 " Linux_Kernel " $2 }' $latestdefaults ) ${menu}"
+		menu="$( awk -F= '$1 ~ /LATEST_2/ {print $1 " Linux_Kernel " $2 }' $latestdefaults ) ${menu}"
 		command=$( "${dialog[@]}" --title "Select Kernel Version" \
 		--item-help --cancel-label "Exit" --default-item "$kver" --menu \
 		"Select a kernel version to use" 0 0 0 \
@@ -884,6 +896,8 @@ create_details()
 			#	echo 'PATCHVER=${patchversion}'
 			#fi
 			) > $detailsdefaults
+			;;
+		expert)
 			;;
 		*)
 			echo "I don't know what the hell is $mode"
