Webmin with patches for automatic install, random port and password.

diff --git a/collab/webmin/webmin.patch b/collab/webmin/webmin.patch
--- a/collab/webmin/webmin.patch
+++ b/collab/webmin/webmin.patch
@@ -1,7 +1,7 @@
 diff -urN webmin-0.970/setup.sh webmin/setup.sh
 --- webmin-0.970/setup.sh	2002-05-07 01:08:45.000000000 -0400
-+++ webmin/setup.sh	2002-05-27 19:29:53.000000000 -0400
-@@ -46,7 +46,7 @@
++++ webmin/setup.sh	2002-05-28 10:25:19.000000000 -0400
+@@ -46,9 +46,11 @@
  echo "Unless you want to run multiple versions of Webmin at the same time"
  echo "you can just accept the defaults."
  echo ""
@@ -9,8 +9,12 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
 +printf "Config file directory [${config_dir:-/etc/webmin}]: "
  if [ "$config_dir" = "" ]; then
  	read config_dir
++else
++	echo ""
  fi
-@@ -133,7 +133,7 @@
+ if [ "$config_dir" = "" ]; then
+ 	config_dir=/etc/webmin
+@@ -133,9 +135,11 @@
  	fi
  
  	# Ask for log directory
@@ -18,8 +22,12 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
 +	printf "Log file directory [${var_dir:-/var/webmin}]: "
  	if [ "$var_dir" = "" ]; then
  		read var_dir
++	else
++		echo ""
  	fi
-@@ -183,7 +183,7 @@
+ 	if [ "$var_dir" = "" ]; then
+ 		var_dir=/var/webmin
+@@ -183,7 +187,7 @@
  				exit 4
  			fi
  		else
@@ -28,7 +36,7 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
  			read perl
  			if [ "$perl" = "" ]; then
  				perl=$perldef
-@@ -256,7 +256,7 @@
+@@ -256,12 +260,14 @@
  	echo " - If the webserver should use SSL (if your system supports it)."
  	echo " - Whether to start webmin at boot time."
  	echo ""
@@ -37,7 +45,14 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
  	if [ "$port" = "" ]; then
  		read port
  		if [ "$port" = "" ]; then
-@@ -280,7 +280,7 @@
+ 			port=10000
+ 		fi
++	else
++		echo ""
+ 	fi
+ 	if [ $port -lt 1 ]; then
+ 		echo "ERROR: $port is not a valid port number"
+@@ -280,12 +286,14 @@
  		echo ""
  		exit 13
  	fi
@@ -46,7 +61,14 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
  	if [ "$login" = "" ]; then
  		read login
  		if [ "$login" = "" ]; then
-@@ -293,7 +293,7 @@
+ 			login="admin"
+ 		fi
++	else
++		echo ""
+ 	fi
+ 	echo $login | grep : >/dev/null
+ 	if [ "$?" = "0" ]; then
+@@ -293,7 +301,7 @@
  		echo ""
  		exit 14
  	fi
@@ -55,8 +77,12 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
  	if [ "$password" = "" -a "$crypt" = "" ]; then
  		stty -echo
  		read password
-@@ -317,7 +317,7 @@
+@@ -315,14 +323,18 @@
+ 			echo ""
+ 			exit 14
  		fi
++	else
++		echo ""
  	fi
  	defhost=`hostname`
 -	printf "Web server host name (default $defhost): "
@@ -64,7 +90,14 @@ diff -urN webmin-0.970/setup.sh webmin/setup.sh
  	if [ "$host" = "" ]; then
  		read host
  		if [ "$host" = "" ]; then
-@@ -368,7 +368,7 @@
+ 			host=$defhost
+ 		fi
++	else
++		echo ""
+ 	fi
+ 	if [ "$ssl" = "" ]; then
+ 		ssl=0
+@@ -368,7 +380,7 @@
  	echo "addtype_cgi=internal/cgi" >> $cfile
  	echo "realm=Webmin Server" >> $cfile
  	echo "logfile=$var_dir/miniserv.log" >> $cfile
