* More cleanup...seems to be working well now. :)

diff --git a/mail/postfix/BUILD b/mail/postfix/BUILD
--- a/mail/postfix/BUILD
+++ b/mail/postfix/BUILD
@@ -1,6 +1,6 @@
-create_account postfix   &&
-create_account postdrop  &&
-create_account mail      &&
+create_account  postfix   &&
+create_account  postdrop  &&
+create_account  mail      &&
  
 mkdir  -p         ${INSTALL_ROOT}/var/spool/mail    &&
 chmod  1777       ${INSTALL_ROOT}/var/spool/mail    &&
@@ -37,8 +37,7 @@ if  [  "$SSL"  ==  "y"  ];  then
   message "${MESSAGE_COLOR}OpenSSL detected: Using OpenSSL ${DEFAULT_COLOR}"
 fi  &&
 
-case $SSL_TLS in
-  y|Y)	
+if  [  "$SSL_TLS"  ==  "y"  ];  then
     message "${MESSAGE_COLOR}Trying to patch Postfix for SSL/TLS support ${DEFAULT_COLOR}"  &&
     patch -Np1 < $SOURCE2_DIRECTORY/pfixtls.diff  || PATCH_FAILED=true  &&
     if [ "$PATCH_FAILED" == "true" ]; then
@@ -46,23 +45,26 @@ case $SSL_TLS in
       message "and answer no to the TLS/SSL patch question.${DEFAULT_COLOR}"  &&
       exit 1
     fi
-esac  &&
-
-if  [  "$PGSQL"  ==  "y"  ];  then
-    message "${MESSAGE_COLOR}Trying to patch for PostgreSQL support${DEFAULT_COLOR}"  &&
-    patch -Np1 < $SOURCE3_DIRECTORY/$SOURCE3  || PATCH_FAILED=true  &&
-    if [ "$PATCH_FAILED" == "true" ]; then
-      message "${MESSAGE_COLOR}Patch failed... please do a cast -r -c postfix"  &&
-      message "and answer no to the Postgresql patch question.${DEFAULT_COLOR}"  &&
-      exit 1
-    fi  &&
-
-    AUXLIBS="$AUXLIBS /usr/lib/libpq.a -lcrypt"  &&
-    CCARGS="$CCARGS  -DHAS_PGSQL -I/usr/include/postgresql"  &&
-    mkdir -p ${INSTALL_ROOT}/usr/doc/$SPELL  &&
-    mkdir -p ${INSTALL_ROOT}/usr/doc/$SPELL/$NAME4  &&
-    cp -r $SOURCE4_DIRECTORY/$NAME4/* ${INSTALL_ROOT}/usr/doc/$SPELL/$NAME4
 fi  &&
+
+#
+#  The PostgreSQL patch is outdated
+#
+#if  [  "$PGSQL"  ==  "y"  ];  then
+  message "${MESSAGE_COLOR}Trying to patch for PostgreSQL support${DEFAULT_COLOR}"  &&
+#  patch -Np1 < $SOURCE3_DIRECTORY/$SOURCE3  || PATCH_FAILED=true  &&
+#  if [ "$PATCH_FAILED" == "true" ]; then
+#      message "${MESSAGE_COLOR}Patch failed... please do a cast -r -c postfix"  &&
+#      message "and answer no to the Postgresql patch question.${DEFAULT_COLOR}"  &&
+#      exit 1
+#    fi  &&
+
+#    AUXLIBS="$AUXLIBS /usr/lib/libpq.a -lcrypt"  &&
+#    CCARGS="$CCARGS  -DHAS_PGSQL -I/usr/include/postgresql"  &&
+#    mkdir -p ${INSTALL_ROOT}/usr/doc/$SPELL  &&
+#    mkdir -p ${INSTALL_ROOT}/usr/doc/$SPELL/$NAME4  &&
+#    cp -r $SOURCE4_DIRECTORY/$NAME4/* ${INSTALL_ROOT}/usr/doc/$SPELL/$NAME4
+#fi  &&
 
 if  [  "$VDA"  ==  "y"  ];  then
     message "${MESSAGE_COLOR}Trying to patch Postfix with VDA support${DEFAULT_COLOR}"  &&
